import AMR2FOL

main = do
 putStrLn        "\n"
 print           "(b / bark-01 :ARG0 (d / dog))"
 putStr          "\n"
 print $ process "(b / bark-01 :ARG0 (d / dog))"
 putStrLn        "\n"
 print           "(s / scratch-01 :ARG0 (d \\ dog) :ARG1 d)"
 putStr          "\n"
 print $ process "(s / scratch-01 :ARG0 (d \\ dog) :ARG1 d)"
 putStrLn        "\n"
 print           "(s / scratch-01 :ARG0 (d \\ dog :quant (e / every) :mod (b / brown)) :ARG1 d)"
 putStr          "\n"
 print $ process "(s / scratch-01 :ARG0 (d \\ dog :quant (e / every) :mod (b / brown)) :ARG1 d)"
 putStrLn        "\n"
 print           "(m / meow-01 :ARG0 (d \\ dog :quant (e / every) :polarity (n / -)))"
 putStr          "\n"
 print $ process "(m / meow-01 :ARG0 (d \\ dog :quant (e / every) :polarity (n / -)))"
 putStrLn        "\n"
 print           "(l / love-01 :ARG0 (f \\ farmer :quant (e / every) :ARG0-of (o \\ own-01 :ARG1 (d \\ donkey))) :ARG1 d)"
 putStr          "\n"
 print $ process "(l / love-01 :ARG0 (f \\ farmer :quant (e / every) :ARG0-of (o \\ own-01 :ARG1 (d \\ donkey))) :ARG1 d)"
 putStrLn        "\n"
